"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 100
add_newline = false
format = "$all"

[os]
disabled = true

[username]
disabled = false
show_always = true
format = "[$user]($style) at "

[hostname]
disabled = false
ssh_only = false
format = "[$ssh_symbol$hostname]($style) "

[shell]
disabled = false
fish_indicator = "fish"

[python]
disabled = true

[nodejs]
disabled = true

[c]
disabled = true

[swift]
disabled = true

